/// <reference lib="webworker" />
// src/serviceWorker.ts - Custom Service Worker for Prioritize PWA
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache static images (Cache First)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 })], // 30 days
  })
);

// Cache Google Fonts (Cache First)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 365 * 24 * 60 * 60 })], // 1 year
  })
);

// API GET requests - Tasks (Network First with fallback)
registerRoute(
  ({ url, request }) => url.pathname.includes('/api/v1/tasks') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-tasks-get',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 300 })], // 5 minutes
  })
);

// API GET requests - All other API (Stale While Revalidate)
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/v1/') && request.method === 'GET',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 600 })], // 10 minutes
  })
);

// Offline mutations - Queue in IndexedDB via Background Sync
const bgSyncPlugin = new BackgroundSyncPlugin('task-queue', {
  maxRetentionTime: 24 * 60, // 24 hours in minutes
  onSync: async ({ queue }) => {
    console.log('[SW] Background sync triggered, processing queue...');
    await queue.replayRequests();
    console.log('[SW] Queue processed successfully');
  },
});

// POST /api/v1/tasks - Create task (with background sync)
registerRoute(
  ({ url, request }) => url.pathname === '/api/v1/tasks' && request.method === 'POST',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST'
);

// PUT /api/v1/tasks/:id - Update task (with background sync)
registerRoute(
  ({ url, request }) => url.pathname.match(/^\/api\/v1\/tasks\/\d+$/) && request.method === 'PUT',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'PUT'
);

// DELETE /api/v1/tasks/:id - Delete task (with background sync)
registerRoute(
  ({ url, request }) => url.pathname.match(/^\/api\/v1\/tasks\/\d+$/) && request.method === 'DELETE',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'DELETE'
);

// Skip waiting and claim clients immediately
self.addEventListener('install', () => {
  console.log('[SW] Service Worker installing...');
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating...');
  event.waitUntil(self.clients.claim());
});

// Listen for messages from the main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});